[theme]
base = "light"
primaryColor = "#1F4B44"
backgroundColor = "#F8FAF8"
secondaryBackgroundColor = "#FFFFFF"
textColor = "#1C2521"
font = "sans serif"

[server]
headless = true
enableCORS = false
enableXsrfProtection = false
runOnSave = true
